path_classifiers:
  test:
    - exclude: 'locale/*.c'

queries:
  - exclude: cpp/integer-multiplication-cast-to-long
  - exclude: cpp/missing-header-guard
  - exclude: cpp/short-global-name
  - exclude: cpp/tainted-format-string
  - exclude: cpp/toctou-race-condition
  - exclude: cpp/cleartext-transmission
  - exclude: cpp/system-data-exposure
  - exclude: cpp/command-line-injection
